### ISSUE TITLE
CI has rotted badly

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/examples-go#46]
```
21:34 $ make test
go test ./...
# github.com/cockroachdb/examples-go/filesystem
filesystem/block_test.go:38: s.PGAddr undefined (type *server.TestServer has no field or method PGAddr)
# github.com/cockroachdb/examples-go/bank/kv_bank
bank/kv_bank/main.go:274: undefined: client.Open
make: *** [test] Error 2
```

Also, the characteristic CircleCI "10 minutes without output from docker pull" reigns supreme: https://circleci.com/gh/cockroachdb/examples-go/80

**Comment by mberhault** [comment]
the 10m timeout seems to be due to:
```
Pulling repository docker.io/cockroachdb/builder
2c16324bce28: Layer already being pulled by another client. Waiting. 
command build/circle-test.sh took more than 10 minutes since last output
```

odd.

**Comment by tamird** [comment]
This was fixed in the main repo by upgrading to docker 1.10
https://github.com/cockroachdb/cockroach/commit/96425adc31030ea5c39a2516957be9ce854a32a4

**Comment by mberhault** [comment]
ah. cool. I was trying that as we speak

**Comment by mberhault** [comment]
yay! progress: https://circleci.com/gh/cockroachdb/examples-go/83

**Comment by mberhault** [comment]
re-opening this. the current timeouts are due to the fact that circle-ci is using a 5-day old version of cockroachdb/cockroach. This is before a lot of the port rework, so I think the client is just sitting there spinning.
Any idea why that would happen? wouldn't the "go get ./..." the deps override take care of it?

**Comment by tschottdorf** [comment]
`go get -u ./...` to force the update?

**Comment by mberhault** [comment]
yeah. but when I did that with `-t`, bad things happened: https://circleci.com/gh/cockroachdb/examples-go/92
the tests are the one pulling in the testserver and therefore cockroachdb.

**Comment by mberhault** [comment]
but mostly, I was wondering why circle-ci is caching this. is it supposed to?
